name: Selenium Pytest + Xray Cloud

on:
  push:
    branches:
      - main
      - 'release/*'
  schedule:
    - cron: '0 0 * * *'   # nightly

jobs:

  smoke-tests:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || pip install selenium pytest

      - name: Run smoke tests
        run: |
          mkdir -p test-results
          pytest -m smoke --junitxml=test-results/results.xml

      - name: Upload results to Xray Cloud
        uses: mikepenz/xray-action@v3
        with:
          xrayCloud: true
          username: ${{ secrets.XRAY_CLIENT_ID }}
          password: ${{ secrets.XRAY_CLIENT_SECRET }}
          testFormat: "junit"
          testPaths: "test-results/results.xml"
          projectKey: "COM"
          testExecKey: "COM-4"


  regression-tests:
    if: (github.event_name == 'push' && startsWith(github.ref, 'refs/heads/release/')) || (github.event_name == 'schedule')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || pip install selenium pytest

      - name: Run full regression tests
        run: |
          mkdir -p test-results
          pytest --junitxml=test-results/results.xml

      - name: Upload results to Xray Cloud
        uses: mikepenz/xray-action@v3
        with:
          xrayCloud: true
          username: ${{ secrets.XRAY_CLIENT_ID }}
          password: ${{ secrets.XRAY_CLIENT_SECRET }}
          testFormat: "junit"
          testPaths: "test-results/results.xml"
          projectKey: "COM"
          testExecKey: "COM-4"
